run_id: demo_scaffold
dataset: datasets/demo_conversations.jsonl
providers:
  primary: openai:gpt-4o-mini
persona_pack: configs/persona/default.yaml
scorers:
  authenticity:
    embedding_model: intfloat/e5-small-v2
  safety:
    keyword_lists: configs/safety_keywords.yaml
  stability:
    window: 3
report:
  out_dir: reports/
