run_id: demo_scaffold
model: openai:gpt-4o-mini
compare_model: null
dataset: ../datasets/demo_conversations.jsonl
persona: persona/default.yaml
keywords: safety_keywords.yaml
embedding: hashed
judge:
  provider: none
  budget: null
report:
  out_dir: ../reports/
  include_raw: true
